version: '3'
services:
  nodejs-app:
    image: ebe45/nodejs-backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql-db
    networks:
      - mynetwork

  mysql-db:
    image: ebe45/incomes-database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    networks:
      - mynetwork

networks:
  mynetwork: